/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "sw1_aliases.h"
#include "sw1.h"
#include "sw2_aliases.h"
#include "sw2.h"
#include "sw3_aliases.h"
#include "sw3.h"
#include "sw4_aliases.h"
#include "sw4.h"
#include "sw5_aliases.h"
#include "sw5.h"
#include "led1_aliases.h"
#include "led1.h"
#include "led3_aliases.h"
#include "led3.h"
#include "led2_aliases.h"
#include "led2.h"
#include "led4_aliases.h"
#include "led4.h"
#include "led5_aliases.h"
#include "led5.h"
#include "led6_aliases.h"
#include "led6.h"
#include "led7_aliases.h"
#include "led7.h"
#include "led8_aliases.h"
#include "led8.h"
#include "led9_aliases.h"
#include "led9.h"
#include "led10_aliases.h"
#include "led10.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

